In [30]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
n = 1
result = []
for i in range(1, 11):
    n = i * 2
    if i == 5:
        continue
    elif i == 8:
        break
    result.append(n)

In [3]:
print(result)

[2, 4, 6, 8, 12, 14]

In [4]:
score = [80, 60, 70, 50, 100, 95, 40, 75, 90, 65, 90, 100]
len(score)

12

In [9]:
a = sum(score) / len(score)
print(a)

76.25

In [16]:
print(np.mean(score))
print(max(score))
print(min(score))

76.25
100
40

In [25]:
!pip install jupyterthemes

Requirement already satisfied: jupyterthemes in c:\users\user\anaconda3\lib\site-packages (0.20.0)
Requirement already satisfied: notebook>=5.6.0 in c:\users\user\anaconda3\lib\site-packages (from jupyterthemes) (6.4.8)
Requirement already satisfied: lesscpy>=0.11.2 in c:\users\user\anaconda3\lib\site-packages (from jupyterthemes) (0.15.1)
Requirement already satisfied: matplotlib>=1.4.3 in c:\users\user\anaconda3\lib\site-packages (from jupyterthemes) (3.5.1)
Requirement already satisfied: ipython>=5.4.1 in c:\users\user\anaconda3\lib\site-packages (from jupyterthemes) (8.2.0)
Requirement already satisfied: jupyter-core in c:\users\user\anaconda3\lib\site-packages (from jupyterthemes) (4.9.2)
Requirement already satisfied: prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0 in c:\users\user\anaconda3\lib\site-packages (from ipython>=5.4.1->jupyterthemes) (3.0.20)
Requirement already satisfied: decorator in c:\users\user\anaconda3\lib\site-packages (from ipython>=5.4.1->jupyterthemes) (5.1.1)
Requirement already satisfied: pickleshare in c:\users\user\anaconda3\lib\site-packages (from ipython>=5.4.1->jupyterthemes) (0.7.5)
Requirement already satisfied: stack-data in c:\users\user\anaconda3\lib\site-packages (from ipython>=5.4.1->jupyterthemes) (0.2.0)
Requirement already satisfied: pygments>=2.4.0 in c:\users\user\anaconda3\lib\site-packages (from ipython>=5.4.1->jupyterthemes) (2.11.2)
Requirement already satisfied: colorama in c:\users\user\anaconda3\lib\site-packages (from ipython>=5.4.1->jupyterthemes) (0.4.4)
Requirement already satisfied: traitlets>=5 in c:\users\user\anaconda3\lib\site-packages (from ipython>=5.4.1->jupyterthemes) (5.1.1)
Requirement already satisfied: backcall in c:\users\user\anaconda3\lib\site-packages (from ipython>=5.4.1->jupyterthemes) (0.2.0)
Requirement already satisfied: jedi>=0.16 in c:\users\user\anaconda3\lib\site-packages (from ipython>=5.4.1->jupyterthemes) (0.18.1)
Requirement already satisfied: setuptools>=18.5 in c:\users\user\anaconda3\lib\site-packages (from ipython>=5.4.1->jupyterthemes) (61.2.0)
Requirement already satisfied: matplotlib-inline in c:\users\user\anaconda3\lib\site-packages (from ipython>=5.4.1->jupyterthemes) (0.1.2)
Requirement already satisfied: parso<0.9.0,>=0.8.0 in c:\users\user\anaconda3\lib\site-packages (from jedi>=0.16->ipython>=5.4.1->jupyterthemes) (0.8.3)
Requirement already satisfied: ply in c:\users\user\anaconda3\lib\site-packages (from lesscpy>=0.11.2->jupyterthemes) (3.11)
Requirement already satisfied: packaging>=20.0 in c:\users\user\anaconda3\lib\site-packages (from matplotlib>=1.4.3->jupyterthemes) (21.3)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\user\anaconda3\lib\site-packages (from matplotlib>=1.4.3->jupyterthemes) (4.25.0)
Requirement already satisfied: cycler>=0.10 in c:\users\user\anaconda3\lib\site-packages (from matplotlib>=1.4.3->jupyterthemes) (0.11.0)
Requirement already satisfied: numpy>=1.17 in c:\users\user\anaconda3\lib\site-packages (from matplotlib>=1.4.3->jupyterthemes) (1.21.5)
Requirement already satisfied: pillow>=6.2.0 in c:\users\user\anaconda3\lib\site-packages (from matplotlib>=1.4.3->jupyterthemes) (9.0.1)
Requirement already satisfied: pyparsing>=2.2.1 in c:\users\user\anaconda3\lib\site-packages (from matplotlib>=1.4.3->jupyterthemes) (3.0.4)
Requirement already satisfied: kiwisolver>=1.0.1 in c:\users\user\anaconda3\lib\site-packages (from matplotlib>=1.4.3->jupyterthemes) (1.3.2)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\user\anaconda3\lib\site-packages (from matplotlib>=1.4.3->jupyterthemes) (2.8.2)
Requirement already satisfied: Send2Trash>=1.8.0 in c:\users\user\anaconda3\lib\site-packages (from notebook>=5.6.0->jupyterthemes) (1.8.0)
Requirement already satisfied: terminado>=0.8.3 in c:\users\user\anaconda3\lib\site-packages (from notebook>=5.6.0->jupyterthemes) (0.13.1)
Requirement already satisfied: jupyter-client>=5.3.4 in c:\users\user\anaconda3\lib\site-packages (from notebook>=5.6.0->jupyterthemes) (6.1.12)
Requirement already satisfied: ipython-genutils in c:\users\user\anaconda3\lib\site-packages (from notebook>=5.6.0->jupyterthemes) (0.2.0)
Requirement already satisfied: nbformat in c:\users\user\anaconda3\lib\site-packages (from notebook>=5.6.0->jupyterthemes) (5.3.0)
Requirement already satisfied: jinja2 in c:\users\user\anaconda3\lib\site-packages (from notebook>=5.6.0->jupyterthemes) (2.11.3)
Requirement already satisfied: argon2-cffi in c:\users\user\anaconda3\lib\site-packages (from notebook>=5.6.0->jupyterthemes) (21.3.0)
Requirement already satisfied: nbconvert in c:\users\user\anaconda3\lib\site-packages (from notebook>=5.6.0->jupyterthemes) (6.4.4)
Requirement already satisfied: tornado>=6.1 in c:\users\user\anaconda3\lib\site-packages (from notebook>=5.6.0->jupyterthemes) (6.1)
Requirement already satisfied: prometheus-client in c:\users\user\anaconda3\lib\site-packages (from notebook>=5.6.0->jupyterthemes) (0.13.1)
Requirement already satisfied: pyzmq>=17 in c:\users\user\anaconda3\lib\site-packages (from notebook>=5.6.0->jupyterthemes) (22.3.0)
Requirement already satisfied: nest-asyncio>=1.5 in c:\users\user\anaconda3\lib\site-packages (from notebook>=5.6.0->jupyterthemes) (1.5.5)
Requirement already satisfied: ipykernel in c:\users\user\anaconda3\lib\site-packages (from notebook>=5.6.0->jupyterthemes) (6.9.1)
Requirement already satisfied: pywin32>=1.0 in c:\users\user\anaconda3\lib\site-packages (from jupyter-core->jupyterthemes) (302)
Requirement already satisfied: wcwidth in c:\users\user\anaconda3\lib\site-packages (from prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0->ipython>=5.4.1->jupyterthemes) (0.2.5)
Requirement already satisfied: six>=1.5 in c:\users\user\anaconda3\lib\site-packages (from python-dateutil>=2.7->matplotlib>=1.4.3->jupyterthemes) (1.16.0)
Requirement already satisfied: pywinpty>=1.1.0 in c:\users\user\anaconda3\lib\site-packages (from terminado>=0.8.3->notebook>=5.6.0->jupyterthemes) (2.0.2)
Requirement already satisfied: argon2-cffi-bindings in c:\users\user\anaconda3\lib\site-packages (from argon2-cffi->notebook>=5.6.0->jupyterthemes) (21.2.0)
Requirement already satisfied: cffi>=1.0.1 in c:\users\user\anaconda3\lib\site-packages (from argon2-cffi-bindings->argon2-cffi->notebook>=5.6.0->jupyterthemes) (1.15.0)
Requirement already satisfied: pycparser in c:\users\user\anaconda3\lib\site-packages (from cffi>=1.0.1->argon2-cffi-bindings->argon2-cffi->notebook>=5.6.0->jupyterthemes) (2.21)
Requirement already satisfied: debugpy<2.0,>=1.0.0 in c:\users\user\anaconda3\lib\site-packages (from ipykernel->notebook>=5.6.0->jupyterthemes) (1.5.1)
Requirement already satisfied: MarkupSafe>=0.23 in c:\users\user\anaconda3\lib\site-packages (from jinja2->notebook>=5.6.0->jupyterthemes) (2.0.1)
Requirement already satisfied: beautifulsoup4 in c:\users\user\anaconda3\lib\site-packages (from nbconvert->notebook>=5.6.0->jupyterthemes) (4.11.1)
Requirement already satisfied: entrypoints>=0.2.2 in c:\users\user\anaconda3\lib\site-packages (from nbconvert->notebook>=5.6.0->jupyterthemes) (0.4)
Requirement already satisfied: nbclient<0.6.0,>=0.5.0 in c:\users\user\anaconda3\lib\site-packages (from nbconvert->notebook>=5.6.0->jupyterthemes) (0.5.13)
Requirement already satisfied: pandocfilters>=1.4.1 in c:\users\user\anaconda3\lib\site-packages (from nbconvert->notebook>=5.6.0->jupyterthemes) (1.5.0)
Requirement already satisfied: jupyterlab-pygments in c:\users\user\anaconda3\lib\site-packages (from nbconvert->notebook>=5.6.0->jupyterthemes) (0.1.2)
Requirement already satisfied: bleach in c:\users\user\anaconda3\lib\site-packages (from nbconvert->notebook>=5.6.0->jupyterthemes) (4.1.0)
Requirement already satisfied: mistune<2,>=0.8.1 in c:\users\user\anaconda3\lib\site-packages (from nbconvert->notebook>=5.6.0->jupyterthemes) (0.8.4)
Requirement already satisfied: testpath in c:\users\user\anaconda3\lib\site-packages (from nbconvert->notebook>=5.6.0->jupyterthemes) (0.5.0)
Requirement already satisfied: defusedxml in c:\users\user\anaconda3\lib\site-packages (from nbconvert->notebook>=5.6.0->jupyterthemes) (0.7.1)
Requirement already satisfied: fastjsonschema in c:\users\user\anaconda3\lib\site-packages (from nbformat->notebook>=5.6.0->jupyterthemes) (2.15.1)
Requirement already satisfied: jsonschema>=2.6 in c:\users\user\anaconda3\lib\site-packages (from nbformat->notebook>=5.6.0->jupyterthemes) (4.4.0)
Requirement already satisfied: pyrsistent!=0.17.0,!=0.17.1,!=0.17.2,>=0.14.0 in c:\users\user\anaconda3\lib\site-packages (from jsonschema>=2.6->nbformat->notebook>=5.6.0->jupyterthemes) (0.18.0)
Requirement already satisfied: attrs>=17.4.0 in c:\users\user\anaconda3\lib\site-packages (from jsonschema>=2.6->nbformat->notebook>=5.6.0->jupyterthemes) (21.4.0)
Requirement already satisfied: soupsieve>1.2 in c:\users\user\anaconda3\lib\site-packages (from beautifulsoup4->nbconvert->notebook>=5.6.0->jupyterthemes) (2.3.1)
Requirement already satisfied: webencodings in c:\users\user\anaconda3\lib\site-packages (from bleach->nbconvert->notebook>=5.6.0->jupyterthemes) (0.5.1)
Requirement already satisfied: executing in c:\users\user\anaconda3\lib\site-packages (from stack-data->ipython>=5.4.1->jupyterthemes) (0.8.3)
Requirement already satisfied: pure-eval in c:\users\user\anaconda3\lib\site-packages (from stack-data->ipython>=5.4.1->jupyterthemes) (0.2.2)
Requirement already satisfied: asttokens in c:\users\user\anaconda3\lib\site-packages (from stack-data->ipython>=5.4.1->jupyterthemes) (2.0.5)

In [27]:
!jt -l

Available Themes:
   chesterish
   grade3
   gruvboxd
   gruvboxl
   monokai
   oceans16
   onedork
   solarizedd
   solarizedl

In [5]:
!jt -t chesterish

In [6]:
!jt -t monokai -f roboto -fs 12 -nf opensans -nfs 13 -ofs 12 -cellw 90% -lineh 150 -T -N -kl

Available Themes:
   chesterish
   grade3
   gruvboxd
   gruvboxl
   monokai
   oceans16
   onedork
   solarizedd
   solarizedl

In [3]:
a = 1

In [12]:
def bartest():
    global a
    a += 1

In [13]:
print(bartest())
print(a)

None
6

In [26]:
re = []
def a(x):
    num = list(range(1 , x+1))
    b = 1
    for i in num:
        b = b*i
        print(b)
        re.append(b)

In [27]:
a(10)

1
2
6
24
120
720
5040
40320
362880
3628800

In [34]:
titanic = pd.read_csv("C:/Users/USER/Desktop/data/train.csv")

In [37]:
titanic

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [36]:
titanic.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [50]:
titanic.groupby("Sex")["Survived"].mean()

Sex
female    0.742038
male      0.188908
Name: Survived, dtype: float64

In [51]:
titanic.groupby("Pclass")["Fare"].mean()

Pclass
1    84.154687
2    20.662183
3    13.675550
Name: Fare, dtype: float64

In [39]:
titanic['Fare'].describe()

count    891.000000
mean      32.204208
std       49.693429
min        0.000000
25%        7.910400
50%       14.454200
75%       31.000000
max      512.329200
Name: Fare, dtype: float64

In [44]:
titanic1 = titanic.drop(columns=['Embarked'])

In [47]:
titanic1

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN
...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN